//! Generates the committed Inter metric tables (specs/text-measurement.md#font-tables).
//!
//! Reads `input/Inter-Regular.ttf` and `input/Inter-SemiBold.ttf`, refuses any file whose
//! SHA-256 differs from the pinned value (specs/supply-chain.md#controls), and writes
//! `crates/merlion-render/src/text/tables.rs`: per weight, the advance of every covered
//! code point, the pair kerning of the `kern` feature in class form, and the vertical
//! metrics browsers use for the font.
//!
//! Usage (from the repository root):
//!
//! ```text
//! cargo run -p fontgen --release              # regenerate tables.rs
//! cargo run -p fontgen --release -- --check   # fail if tables.rs is stale
//! cargo run -p fontgen --release -- --unicodes  # print the coverage for pyftsubset
//! ```

mod sha256;

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use ttf_parser::gpos::{PairAdjustment, PositioningSubtable};
use ttf_parser::{Face, GlyphId, Tag};

/// Pinned inputs: Inter 4.1 static TTFs (OFL-1.1).
const INPUTS: [(&str, &str, &str); 2] = [
    (
        "REGULAR",
        "Inter-Regular.ttf",
        "40d692fce188e4471e2b3cba937be967878f631ad3ebbbdcd587687c7ebe0c82",
    ),
    (
        "SEMIBOLD",
        "Inter-SemiBold.ttf",
        "78a843fade9d4612a5567302fb595b56976eb5fcebf4fea5a5912d638bafcde3",
    ),
];

/// Coverage (specs/text-measurement.md#font-tables): Basic Latin (printable ASCII),
/// Latin-1 Supplement, Latin Extended-A/B, Greek and Coptic, Cyrillic, General
/// Punctuation, Arrows and Box Drawing. The WOFF2 subset uses the same ranges.
const COVERAGE: [(u32, u32); 9] = [
    (0x0020, 0x007E),
    (0x00A0, 0x00FF),
    (0x0100, 0x017F),
    (0x0180, 0x024F),
    (0x0370, 0x03FF),
    (0x0400, 0x04FF),
    (0x2000, 0x206F),
    (0x2190, 0x21FF),
    (0x2500, 0x257F),
];

/// Characters the core strips or drops before measuring (bidi controls,
/// specs/svg-output.md#text); they get no table entry.
fn excluded(cp: u32) -> bool {
    (0x202A..=0x202E).contains(&cp) || (0x2066..=0x2069).contains(&cp)
}

struct Metrics {
    units_per_em: u16,
    ascender: i16,
    descender: i16,
    line_gap: i16,
    avg_advance: u16,
    /// (code point, advance, left kerning class, right kerning class), sorted by code point.
    glyphs: Vec<(u32, u16, u16, u16)>,
    left_classes: u16,
    right_classes: u16,
    /// Non-zero class-pair values, sorted by (left, right).
    kern: Vec<(u16, u16, i16)>,
    kern_source: &'static str,
    typo_metrics: bool,
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let root = repo_root();
    if args.iter().any(|a| a == "--unicodes") {
        println!("{}", unicodes_arg());
        return ExitCode::SUCCESS;
    }
    let check = args.iter().any(|a| a == "--check");
    match generate(&root) {
        Ok(src) => {
            let out = root.join("crates/merlion-render/src/text/tables.rs");
            if check {
                let current = std::fs::read_to_string(&out).unwrap_or_default();
                if current != src {
                    eprintln!(
                        "{} is stale; run `cargo run -p fontgen --release`",
                        out.display()
                    );
                    return ExitCode::FAILURE;
                }
                eprintln!("{} is up to date", out.display());
            } else if let Err(e) = std::fs::write(&out, src) {
                eprintln!("cannot write {}: {e}", out.display());
                return ExitCode::FAILURE;
            } else {
                eprintln!("wrote {}", out.display());
            }
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("fontgen: {e}");
            ExitCode::FAILURE
        }
    }
}

/// `tools/fontgen/../..`, independent of the working directory.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn unicodes_arg() -> String {
    COVERAGE
        .iter()
        .map(|(a, b)| format!("U+{a:04X}-{b:04X}"))
        .collect::<Vec<_>>()
        .join(",")
}

fn generate(root: &Path) -> Result<String, String> {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "//! Inter metric tables — generated by tools/fontgen — do not edit.\n//!"
    );
    let mut bodies = String::new();
    for (name, file, pinned) in INPUTS {
        let path = root.join("tools/fontgen/input").join(file);
        let data =
            std::fs::read(&path).map_err(|e| format!("cannot read {}: {e}", path.display()))?;
        let digest = sha256::hex_digest(&data);
        if digest != pinned {
            return Err(format!(
                "{file}: SHA-256 {digest} differs from the pinned {pinned}; refusing it"
            ));
        }
        let face = Face::parse(&data, 0).map_err(|e| format!("{file}: {e}"))?;
        let m = extract(&face);
        eprintln!(
            "{file}: upem {} asc {} desc {} gap {} (typo metrics: {}), avg {}, {} glyphs, \
             kern {} ({}x{} classes, {} non-zero pairs)",
            m.units_per_em,
            m.ascender,
            m.descender,
            m.line_gap,
            m.typo_metrics,
            m.avg_advance,
            m.glyphs.len(),
            m.kern_source,
            m.left_classes,
            m.right_classes,
            m.kern.len()
        );
        let _ = writeln!(out, "//! {file} SHA-256 {digest}");
        emit(&mut bodies, name, &m);
    }
    let _ = writeln!(out, "//!\n//! Coverage: {}", unicodes_arg());
    out.push_str("\n#![allow(clippy::unreadable_literal)]\n\nuse super::font::FontTable;\n");
    out.push_str(&bodies);
    Ok(out)
}

fn extract(face: &Face) -> Metrics {
    let os2 = face.tables().os2;
    let hhea = face.tables().hhea;
    // Browsers take ascender/descender/lineGap from OS/2 sTypo* when fsSelection bit 7
    // (USE_TYPO_METRICS) is set, else from hhea (macOS) / usWin* (Windows). Inter sets
    // the bit, so every platform agrees on the typo values.
    let typo_metrics = os2.is_some_and(|t| t.use_typographic_metrics());
    let (ascender, descender, line_gap) = match os2 {
        Some(t) if typo_metrics => (
            t.typographic_ascender(),
            t.typographic_descender(),
            t.typographic_line_gap(),
        ),
        _ => (hhea.ascender, hhea.descender, hhea.line_gap),
    };

    // Covered code points and their glyphs.
    let mut cps: Vec<(u32, GlyphId, u16)> = Vec::new();
    for (lo, hi) in COVERAGE {
        for cp in lo..=hi {
            if excluded(cp) {
                continue;
            }
            let Some(ch) = char::from_u32(cp) else {
                continue;
            };
            let Some(g) = face.glyph_index(ch) else {
                continue;
            };
            if g.0 == 0 {
                continue;
            }
            let adv = face.glyph_hor_advance(g).unwrap_or(0);
            cps.push((cp, g, adv));
        }
    }
    // Average over glyphs that advance at all (zero-width spaces and joiners excluded).
    let spacing: Vec<u64> = cps.iter().filter(|c| c.2 > 0).map(|c| c.2 as u64).collect();
    let avg_advance = if spacing.is_empty() {
        face.units_per_em() / 2
    } else {
        ((spacing.iter().sum::<u64>() + spacing.len() as u64 / 2) / spacing.len() as u64) as u16
    };

    // Kerning matrix over glyphs (code points sharing a glyph share rows).
    let mut glyphs: Vec<GlyphId> = cps.iter().map(|c| c.1).collect();
    glyphs.sort();
    glyphs.dedup();
    let (kern_fn, kern_source) = kerning_function(face);
    let n = glyphs.len();
    let mut matrix = vec![0i32; n * n];
    for (i, &g1) in glyphs.iter().enumerate() {
        for (j, &g2) in glyphs.iter().enumerate() {
            matrix[i * n + j] = kern_fn(g1, g2);
        }
    }
    // Class form: glyphs with identical rows share a left class, identical columns a
    // right class. Class 0 is the all-zero row/column.
    let left_of = classify(n, |i| (0..n).map(|j| matrix[i * n + j]).collect());
    let right_of = classify(n, |j| (0..n).map(|i| matrix[i * n + j]).collect());
    let mut pairs: BTreeMap<(u16, u16), i16> = BTreeMap::new();
    for i in 0..n {
        for j in 0..n {
            let v = matrix[i * n + j];
            if v != 0 {
                pairs.insert(
                    (left_of[i], right_of[j]),
                    v.clamp(i16::MIN as i32, i16::MAX as i32) as i16,
                );
            }
        }
    }
    let idx = |g: GlyphId| glyphs.binary_search(&g).unwrap_or(0);
    Metrics {
        units_per_em: face.units_per_em(),
        ascender,
        descender,
        line_gap,
        avg_advance,
        glyphs: cps
            .iter()
            .map(|&(cp, g, adv)| (cp, adv, left_of[idx(g)], right_of[idx(g)]))
            .collect(),
        left_classes: left_of.iter().copied().max().unwrap_or(0) + 1,
        right_classes: right_of.iter().copied().max().unwrap_or(0) + 1,
        kern: pairs.into_iter().map(|((l, r), v)| (l, r, v)).collect(),
        kern_source,
        typo_metrics,
    }
}

/// Groups indices by identical vectors; the all-zero vector is class 0 and the
/// others are numbered in first-seen order, so the result is deterministic.
fn classify(n: usize, vector: impl Fn(usize) -> Vec<i32>) -> Vec<u16> {
    let mut ids: BTreeMap<Vec<i32>, u16> = BTreeMap::new();
    let mut next = 1u16;
    (0..n)
        .map(|i| {
            let v = vector(i);
            if v.iter().all(|&x| x == 0) {
                return 0;
            }
            *ids.entry(v).or_insert_with(|| {
                next += 1;
                next - 1
            })
        })
        .collect()
}

type KernFn<'a> = Box<dyn Fn(GlyphId, GlyphId) -> i32 + 'a>;

/// Pair kerning as a browser applies it with only the `kern` feature on: the GPOS pair
/// adjustment lookups the `kern` feature references (in any script), summed over
/// lookups, first applicable subtable per lookup (OpenType GPOS, LookupType 2). Falls
/// back to the legacy `kern` table when the font has no GPOS `kern` feature.
fn kerning_function<'a>(face: &'a Face<'a>) -> (KernFn<'a>, &'static str) {
    let kern_tag = Tag::from_bytes(b"kern");
    if let Some(gpos) = face.tables().gpos {
        let mut lookups: Vec<u16> = gpos
            .features
            .into_iter()
            .filter(|f| f.tag == kern_tag)
            .flat_map(|f| f.lookup_indices.into_iter())
            .collect();
        lookups.sort_unstable();
        lookups.dedup();
        if !lookups.is_empty() {
            let f = move |g1: GlyphId, g2: GlyphId| -> i32 {
                let mut total = 0i32;
                for &li in &lookups {
                    let Some(lookup) = gpos.lookups.get(li) else {
                        continue;
                    };
                    for sub in lookup.subtables.into_iter::<PositioningSubtable>() {
                        let PositioningSubtable::Pair(pair) = sub else {
                            continue;
                        };
                        if let Some(v) = pair_value(&pair, g1, g2) {
                            total += v;
                            break;
                        }
                    }
                }
                total
            };
            return (Box::new(f), "GPOS kern feature");
        }
    }
    if let Some(kern) = face.tables().kern {
        let f = move |g1: GlyphId, g2: GlyphId| -> i32 {
            kern.subtables
                .into_iter()
                .filter(|s| s.horizontal && !s.variable && !s.has_cross_stream)
                .filter_map(|s| s.glyphs_kerning(g1, g2))
                .map(i32::from)
                .sum()
        };
        return (Box::new(f), "kern table");
    }
    (Box::new(|_, _| 0), "none")
}

/// The advance change a pair subtable applies to `g1 g2`, or `None` when the subtable
/// does not apply (so the next subtable of the lookup is tried).
fn pair_value(pair: &PairAdjustment, g1: GlyphId, g2: GlyphId) -> Option<i32> {
    let cov = pair.coverage().get(g1)?;
    let (v1, v2) = match pair {
        PairAdjustment::Format1 { sets, .. } => sets.get(cov)?.get(g2)?,
        PairAdjustment::Format2 {
            classes, matrix, ..
        } => matrix.get((classes.0.get(g1), classes.1.get(g2)))?,
    };
    Some(v1.x_advance as i32 + v2.x_advance as i32)
}

fn emit(out: &mut String, name: &str, m: &Metrics) {
    let _ = writeln!(
        out,
        "\npub static {name}: FontTable = FontTable {{\n    units_per_em: {},\n    ascender: {},\n    \
         descender: {},\n    line_gap: {},\n    avg_advance: {},\n    left_classes: {},\n    \
         right_classes: {},\n    glyphs: &{name}_GLYPHS,\n    kern: &{name}_KERN,\n}};",
        m.units_per_em,
        m.ascender,
        m.descender,
        m.line_gap,
        m.avg_advance,
        m.left_classes,
        m.right_classes
    );
    let _ = writeln!(
        out,
        "\n/// (code point, advance, left kerning class, right kerning class)\nstatic {name}_GLYPHS: [(u32, u16, u16, u16); {}] = [",
        m.glyphs.len()
    );
    for chunk in m.glyphs.chunks(6) {
        out.push_str("   ");
        for (cp, adv, l, r) in chunk {
            let _ = write!(out, " (0x{cp:04X}, {adv}, {l}, {r}),");
        }
        out.push('\n');
    }
    out.push_str("];\n");
    let _ = writeln!(
        out,
        "\n/// (left class, right class, adjustment in font units)\nstatic {name}_KERN: [(u16, u16, i16); {}] = [",
        m.kern.len()
    );
    for chunk in m.kern.chunks(8) {
        out.push_str("   ");
        for (l, r, v) in chunk {
            let _ = write!(out, " ({l}, {r}, {v}),");
        }
        out.push('\n');
    }
    out.push_str("];\n");
}
