//! Font metric tables and their lookups (specs/text-measurement.md#font-tables).
//!
//! The tables in `tables.rs` are generated by `tools/fontgen` from pinned Inter 4.1
//! files. Each table is a code-point-sorted glyph array plus class-based pair kerning;
//! every lookup is a binary search, so measurement needs no allocation.

use super::Weight;

/// Metrics of one font weight, in font units.
#[derive(Debug)]
pub struct FontTable {
    pub units_per_em: u16,
    /// Top of the line box above the baseline (OS/2 `sTypoAscender`; Inter sets `USE_TYPO_METRICS`).
    pub ascender: i16,
    /// Bottom of the line box below the baseline, negative (OS/2 `sTypoDescender`).
    pub descender: i16,
    pub line_gap: i16,
    /// Mean advance of the covered glyphs that advance; the width of an unmeasured glyph.
    pub avg_advance: u16,
    pub left_classes: u16,
    pub right_classes: u16,
    /// (code point, advance, left kerning class, right kerning class), sorted by code point.
    pub glyphs: &'static [(u32, u16, u16, u16)],
    /// (left class, right class, adjustment), sorted by (left, right); zero pairs omitted.
    pub kern: &'static [(u16, u16, i16)],
}

/// How a code point is measured.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Glyph {
    /// In the table: advance and kerning classes.
    Known { advance: u16, left: u16, right: u16 },
    /// Outside the table, measured at a fixed width in font units (`I010`).
    Fallback { advance: u16 },
    /// A combining mark or variation selector: draws over its base, takes no width.
    ZeroWidth,
}

impl FontTable {
    fn entry(&self, c: char) -> Option<&(u32, u16, u16, u16)> {
        let cp = c as u32;
        self.glyphs
            .binary_search_by(|e| e.0.cmp(&cp))
            .ok()
            .and_then(|i| self.glyphs.get(i))
    }

    /// Advance in font units, or `None` when the code point is outside the table.
    pub fn advance(&self, c: char) -> Option<u16> {
        self.entry(c).map(|e| e.1)
    }

    pub fn glyph(&self, c: char) -> Glyph {
        if let Some(&(_, advance, left, right)) = self.entry(c) {
            return Glyph::Known {
                advance,
                left,
                right,
            };
        }
        if is_zero_width(c) {
            return Glyph::ZeroWidth;
        }
        let advance = if is_wide(c) {
            self.units_per_em
        } else {
            self.avg_advance
        };
        Glyph::Fallback { advance }
    }

    /// Pair adjustment between two kerning classes, in font units.
    pub fn class_kerning(&self, left: u16, right: u16) -> i16 {
        if left == 0 || right == 0 {
            return 0;
        }
        self.kern
            .binary_search_by(|e| (e.0, e.1).cmp(&(left, right)))
            .ok()
            .and_then(|i| self.kern.get(i))
            .map_or(0, |e| e.2)
    }

    /// Pair adjustment between two code points, in font units (0 if either is unknown).
    pub fn kerning(&self, a: char, b: char) -> i16 {
        match (self.entry(a), self.entry(b)) {
            (Some(l), Some(r)) => self.class_kerning(l.2, r.3),
            _ => 0,
        }
    }
}

/// The table for a weight. Bold labels use SemiBold (specs/text-measurement.md#font-tables).
pub fn table(weight: Weight) -> &'static FontTable {
    match weight {
        Weight::Regular => &super::tables::REGULAR,
        Weight::SemiBold => &super::tables::SEMIBOLD,
    }
}

/// CJK, Hangul and fullwidth code points, measured at 1 em when outside the table.
pub fn is_wide(c: char) -> bool {
    matches!(c as u32,
        0x1100..=0x115F       // Hangul Jamo (leading consonants, wide)
        | 0x2E80..=0x303E     // CJK radicals, Kangxi, ideographic description, CJK symbols and punctuation
        | 0x3041..=0x33FF     // Hiragana, Katakana, Bopomofo, Hangul compatibility Jamo, Kanbun, CJK strokes, enclosed CJK, compatibility
        | 0x3400..=0x4DBF     // CJK Extension A
        | 0x4E00..=0x9FFF     // CJK Unified Ideographs
        | 0xA000..=0xA4CF     // Yi
        | 0xA960..=0xA97F     // Hangul Jamo Extended-A
        | 0xAC00..=0xD7A3     // Hangul Syllables
        | 0xF900..=0xFAFF     // CJK Compatibility Ideographs
        | 0xFE30..=0xFE4F     // CJK Compatibility Forms
        | 0xFF00..=0xFF60     // Fullwidth forms
        | 0xFFE0..=0xFFE6     // Fullwidth signs
        | 0x20000..=0x3FFFD   // CJK Extensions B–H, compatibility supplement
    )
}

/// Combining marks and variation selectors: they attach to the preceding glyph and
/// add no advance, so they are measured at 0 and do not count as unmeasured.
pub fn is_zero_width(c: char) -> bool {
    matches!(c as u32,
        0x0300..=0x036F       // Combining Diacritical Marks
        | 0x0483..=0x0489     // Combining Cyrillic
        | 0x1AB0..=0x1AFF     // Combining Diacritical Marks Extended
        | 0x1DC0..=0x1DFF     // Combining Diacritical Marks Supplement
        | 0x20D0..=0x20FF     // Combining Diacritical Marks for Symbols
        | 0xFE00..=0xFE0F     // Variation Selectors
        | 0xFE20..=0xFE2F     // Combining Half Marks
        | 0xE0100..=0xE01EF   // Variation Selectors Supplement
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tables_are_sorted_and_unique() {
        for t in [table(Weight::Regular), table(Weight::SemiBold)] {
            assert!(t.glyphs.windows(2).all(|w| w[0].0 < w[1].0));
            assert!(t
                .kern
                .windows(2)
                .all(|w| (w[0].0, w[0].1) < (w[1].0, w[1].1)));
            assert!(t
                .glyphs
                .iter()
                .all(|g| g.2 < t.left_classes && g.3 < t.right_classes));
        }
    }

    #[test]
    fn both_weights_share_vertical_metrics() {
        let r = table(Weight::Regular);
        let b = table(Weight::SemiBold);
        assert_eq!(r.units_per_em, b.units_per_em);
        assert_eq!(
            (r.ascender, r.descender, r.line_gap),
            (b.ascender, b.descender, b.line_gap)
        );
        assert!(r.ascender > 0 && r.descender < 0);
    }

    #[test]
    fn coverage_includes_every_spec_range() {
        let t = table(Weight::Regular);
        for c in ['A', 'z', ' ', 'é', 'Ł', 'ǅ', 'Ω', 'Ж', '—', '→', '↔', '…'] {
            assert!(t.advance(c).is_some(), "{c:?} missing");
        }
        assert!(t.advance('中').is_none());
        // Inter 4.1 has no Box Drawing glyphs; those fall back to the average advance.
        assert!(t.advance('─').is_none());
    }

    #[test]
    fn av_kerns_negative() {
        let t = table(Weight::Regular);
        assert!(t.kerning('A', 'V') < 0);
        assert!(t.kerning('T', 'o') < 0);
        assert_eq!(t.kerning('l', 'l'), 0);
    }

    #[test]
    fn fallback_widths() {
        let t = table(Weight::Regular);
        assert_eq!(
            t.glyph('中'),
            Glyph::Fallback {
                advance: t.units_per_em
            }
        );
        assert_eq!(
            t.glyph('한'),
            Glyph::Fallback {
                advance: t.units_per_em
            }
        );
        assert_eq!(
            t.glyph('Ａ'),
            Glyph::Fallback {
                advance: t.units_per_em
            }
        );
        assert_eq!(
            t.glyph('א'),
            Glyph::Fallback {
                advance: t.avg_advance
            }
        );
        assert_eq!(t.glyph('\u{0301}'), Glyph::ZeroWidth);
    }

    #[test]
    fn class_zero_never_kerns() {
        let t = table(Weight::SemiBold);
        assert_eq!(t.class_kerning(0, 5), 0);
        assert_eq!(t.class_kerning(5, 0), 0);
    }
}
